package Exceptionhandeling;

import java.util.Arrays;

public class Dummy {

    public static void main(String[] args) throws ArithmeticException{


        int a = 100;

        int b = 0;
        int sum = 0;


//        try {
//            sum = a / b;
//        } catch (ArithmeticException C)
//        {
//            System.out.println(Arrays.toString(C.getStackTrace()));
//          //C.printStackTrace();
//            //throw C;
//
//        }
//finally {
//            System.out.println("all done ");
//        }

        System.out.println("sum is :"+ sum);
    }
}
